# 错误处理

> [【React错误处理】超全指南来了](https://juejin.cn/post/7225076114561253413) 

在React中，未捕获错误会导致 DOM 被卸载, 浏览器无法渲染，出现白屏。



## 防止 Bug

+ 不要相信后端的数据格式，全部做可选链处理



## 捕获 Bug

| 异常类型                               | 同步方法 | 异步方法 | 资源加载 | Promise | async...await |
| -------------------------------------- | -------- | -------- | -------- | ------- | ------------- |
| try catch                              | √        |          |          |         | √             |
| window.onerror                         | √        | √        |          |         |               |
| addEventListener('error')              | √        | √        | √        |         |               |
| addEventListener('unhandledrejection') |          |          |          | √       | √             |

### window.error vs addEventListener('error')

`window.onerror` 和 `addEventListener('error')` 都是用于捕获 JavaScript 运行时错误的机制，但它们之间有一些区别。

1. **触发时机：** `window.onerror` 是一个全局事件处理器，当 JavaScript 运行时发生未被捕获的错误时，会触发该事件。它会捕获整个页面中的所有错误。而 `addEventListener('error')` 是一个事件监听器，可以通过将其添加到特定的元素上来捕获该元素内部发生的错误。
2. **错误信息：** `window.onerror` 会接收到错误的详细信息，包括错误消息、错误来源、行号、列号和错误堆栈等。而 `addEventListener('error')` 只能获得有限的错误信息，通常只包括错误消息和错误来源。
3. **冒泡机制：** `window.onerror` 不会冒泡，它只能捕获全局范围内的错误。而 `addEventListener('error')` 可以通过冒泡机制捕获元素内部的错误，并在事件冒泡到祖先元素时继续触发。
4. **多个处理函数：** `window.onerror` 只能设置一个全局错误处理函数，如果多次设置，只会保留最后一个设置的处理函数。而 `addEventListener('error')` 可以为同一个元素添加多个错误处理函数，它们会按照添加的顺序依次执行。

综上所述，`window.onerror` 是一个全局的错误处理机制，适用于捕获整个页面中的错误。而 `addEventListener('error')` 是针对特定元素的错误处理机制，适用于捕获该元素内部发生的错误，并可以通过事件冒泡机制继续捕获祖先元素的错误。



## 框架

+ React 的 [ErrorBoundary](https://zh-hans.react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) 
  + [Feature Idea: useError hook #14347](https://github.com/facebook/react/issues/14347) 
  + [Why Isn’t X a Hook?](https://overreacted.io/why-isnt-x-a-hook/) 



# React 异常处理机制

> [React异常捕获机制及源码](https://github.com/lizuncong/mini-react/blob/master/docs/%E5%BC%82%E5%B8%B8/React%E5%BC%82%E5%B8%B8%E6%8D%95%E8%8E%B7%E6%9C%BA%E5%88%B6%E5%8F%8A%E6%BA%90%E7%A0%81.md) 

**React 异常处理最重要的目标之一就是，避免吞没用户业务代码的异常，从而保持浏览器的 `Pause on exceptions` 行为**。

+ 为了达到这个目标，React 将用户的所有业务代码包裹在 `invokeGuardedCallback` 函数中执行，比如构造函数，生命周期方法等。
+ 在 `invokeGuardedCallback` 内部：dev 环境下，React 使用 [custom event](https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent ) 以及 [dispatchEvent](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) 模拟 try catch 的行为；而在生产环境中，react 简单的使用了 try catch。